#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
PDS-AutomationSuite Build Selector
Interactive board, hardware revision, and role selection tool with auto-build
"""

import os
import sys
import json
import argparse
import subprocess
import shutil
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# ANSI color codes
class Colors:
    RESET = '\033[0m'
    BOLD = '\033[1m'
    DIM = '\033[2m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    BLUE = '\033[94m'
    WHITE = '\033[97m'

def cprint(msg: str, color: str = Colors.WHITE) -> None:
    """Print colored message"""
    print(f"{color}{msg}{Colors.RESET}")

def header(msg: str) -> None:
    """Print section header"""
    print(f"\n{Colors.CYAN}{Colors.BOLD}{'='*70}{Colors.RESET}")
    print(f"{Colors.CYAN}{Colors.BOLD}{msg:^70}{Colors.RESET}")
    print(f"{Colors.CYAN}{Colors.BOLD}{'='*70}{Colors.RESET}\n")

def success(msg: str) -> None:
    """Print success message"""
    cprint(f"[+] {msg}", Colors.GREEN)

def error(msg: str) -> None:
    """Print error message"""
    cprint(f"[-] {msg}", Colors.RED)

def warning(msg: str) -> None:
    """Print warning message"""
    cprint(f"[!] {msg}", Colors.YELLOW)

def info(msg: str) -> None:
    """Print info message"""
    cprint(f"[*] {msg}", Colors.BLUE)

def has_devcontainer_cli() -> bool:
    """Check if devcontainers CLI is installed"""
    return shutil.which("devcontainer") is not None

def get_devcontainer_path(board: str) -> Optional[Path]:
    """Get the devcontainer path for a board.

    Container name is always DEV-Container-<board_name>, where board_name
    is the directory name under Device/pds/pds_hal/board/.
    e.g.  esp32c3_sm    -> DEV-Container-esp32c3_sm
          esp32_node32s -> DEV-Container-esp32_node32s
    """
    workspace = Path(__file__).parent.parent.parent
    container_path = workspace / "Device" / f"DEV-Container-{board}"
    if container_path.exists():
        return container_path
    return None


def scaffold_role_dir(board: str, hwrev: str, role: str) -> bool:
    """Create minimal pds_process_action.c + usrset_defaults.h for a role that has no dir.

    Without these files, the linker fails with 'undefined reference to pds_role_init'
    after a full compile — a very late and confusing failure.  This function detects
    the missing files before the build starts and writes stubs so the firmware at
    least compiles.  The developer can then fill in telemetry wiring at their leisure.

    Returns True if any file was written (scaffolded), False if both already existed.
    """
    workspace = Path(__file__).parent.parent.parent
    role_dir = workspace / "Device" / "pds" / "pds_hal" / "board" / board / hwrev / role
    pa_file = role_dir / "pds_process_action.c"
    ud_file = role_dir / "usrset_defaults.h"

    if pa_file.exists() and ud_file.exists():
        return False

    role_tag = role.replace("-", "_").upper()
    ts = datetime.utcnow().strftime("%Y-%m-%d UTC")
    role_dir.mkdir(parents=True, exist_ok=True)

    if not ud_file.exists():
        ud_file.write_text(
            f'/**\n'
            f' * @file usrset_defaults.h\n'
            f' * @brief Usrset defaults for {role} — scaffold by build_selector.py ({ts})\n'
            f' *        board: {board} / {hwrev}\n'
            f' */\n'
            f'#ifndef PDS_USRSET_DEFAULTS_H\n'
            f'#define PDS_USRSET_DEFAULTS_H\n'
            f'\n'
            f'#include "pds_usrset.h"\n'
            f'\n'
            f'#ifdef __cplusplus\n'
            f'extern "C" {{\n'
            f'#endif\n'
            f'\n'
            f'static const pds_usrset_default_t pds_usrset_defaults[] = {{\n'
            f'    {{ "telemetry_interval_ms", 5000.0f }},\n'
            f'}};\n'
            f'\n'
            f'#define PDS_USRSET_DEFAULTS_COUNT \\\n'
            f'    ((uint16_t)(sizeof(pds_usrset_defaults) / sizeof(pds_usrset_defaults[0])))\n'
            f'\n'
            f'#ifdef __cplusplus\n'
            f'}}\n'
            f'#endif\n'
            f'\n'
            f'#endif /* PDS_USRSET_DEFAULTS_H */\n',
            encoding="utf-8"
        )

    if not pa_file.exists():
        pa_file.write_text(
            f'/**\n'
            f' * @file pds_process_action.c\n'
            f' * @brief Role scaffold for {role} — auto-generated by build_selector.py ({ts})\n'
            f' *        board: {board} / {hwrev}\n'
            f' *\n'
            f' * SCAFFOLD: This file was missing for this role/hwrev combination and was\n'
            f' * created automatically so the firmware compiles.  Edit the telemetry\n'
            f' * provider below to match your hardware wiring, then rebuild.\n'
            f' */\n'
            f'\n'
            f'#include "freertos/FreeRTOS.h"\n'
            f'#include "esp_log.h"\n'
            f'#include "esp_err.h"\n'
            f'#include "nvs_flash.h"\n'
            f'\n'
            f'#include "pds_usrset.h"\n'
            f'#include "pds_telemetry.h"\n'
            f'#include "usrset_defaults.h"\n'
            f'\n'
            f'static const char *TAG = "{role_tag}_ROLE";\n'
            f'\n'
            f'static esp_err_t {role_tag}_telemetry_provider(pds_teldata_packet_t *packet)\n'
            f'{{\n'
            f'    /* TODO: call pds_telemetry_add_adc/pwm/gpio for each sensor/actuator */\n'
            f'    (void)packet;\n'
            f'    return ESP_OK;\n'
            f'}}\n'
            f'\n'
            f'esp_err_t pds_role_init(void)\n'
            f'{{\n'
            f'    esp_err_t ret = pds_usrset_init(pds_usrset_defaults, PDS_USRSET_DEFAULTS_COUNT);\n'
            f'    if (ret != ESP_OK) {{\n'
            f'        ESP_LOGW(TAG, "pds_usrset_init: %s", esp_err_to_name(ret));\n'
            f'        return ret;\n'
            f'    }}\n'
            f'    ret = pds_usrset_load_nvs();\n'
            f'    if (ret == ESP_ERR_NVS_NOT_FOUND) {{\n'
            f'        ESP_LOGI(TAG, "No saved usrset -- using defaults");\n'
            f'        ret = ESP_OK;\n'
            f'    }} else if (ret != ESP_OK) {{\n'
            f'        ESP_LOGW(TAG, "pds_usrset_load_nvs: %s", esp_err_to_name(ret));\n'
            f'        return ret;\n'
            f'    }}\n'
            f'    pds_telemetry_register_provider({role_tag}_telemetry_provider);\n'
            f'    ESP_LOGI(TAG, "Role init OK -- %d usrset defaults", PDS_USRSET_DEFAULTS_COUNT);\n'
            f'    return ESP_OK;\n'
            f'}}\n'
            f'\n'
            f'esp_err_t pds_process_action(void)\n'
            f'{{\n'
            f'    return ESP_OK;\n'
            f'}}\n',
            encoding="utf-8"
        )

    return True


# ---------------------------------------------------------------------------
# Hardware code registry helpers
# ---------------------------------------------------------------------------

_VALID_CODE_CHARS = set("0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz")


def _code_valid(code: str) -> bool:
    """Return True if code is exactly 3 alphanumeric characters."""
    return len(code) == 3 and all(c in _VALID_CODE_CHARS for c in code)


def resolve_hw_code(board: str, hwrev: str, flash_cfg: dict, flash_cfg_path: Path) -> str:
    """Return the 3-char hardware code for board+hwrev.

    Format: one alphanumeric board-letter + two alphanumeric hwrev chars.
    Examples: C02 (esp32c3_sm / hwrev-002), N01 (esp32_node32s / hwrev-001).

    If no code exists for this combination the user is prompted to assign one.
    The new code is validated (format + uniqueness) and saved back to .flash_config.json.
    """
    import re

    key = f"{board}+{hwrev}"
    codes: dict = flash_cfg.setdefault("hwrev_codes", {})
    versions: dict = flash_cfg.setdefault("versions", {})

    if key in codes:
        return codes[key]

    # ── Prompt user to assign a new code ──────────────────────────────────
    header("New hardware combination detected — assign a firmware code")
    info(f"board : {board}")
    info(f"HW rev   : {hwrev}")
    print()

    if codes:
        cprint("  Existing codes:", Colors.CYAN)
        cprint(f"  {'Code':<6}  board+hwrev", Colors.CYAN)
        cprint("  " + "-" * 40, Colors.CYAN)
        for existing_key, existing_code in sorted(codes.items(), key=lambda x: x[1]):
            ver = versions.get(existing_code, "–")
            cprint(f"  {existing_code:<6}  {existing_key}  (current: {ver})", Colors.WHITE)
        print()

    cprint("  Code format: 3 alphanumeric characters [0-9 A-Z a-z]", Colors.YELLOW)
    cprint("  Convention : <board-letter><2-char-hwrev>", Colors.YELLOW)
    cprint("  Example    : C02  (C = esp32c3_sm, 02 = hwrev-002)", Colors.YELLOW)
    print()

    existing_codes = set(codes.values())
    while True:
        raw = input(f"{Colors.BOLD}  Enter 3-char code for [{board}+{hwrev}]: {Colors.RESET}").strip()
        if not _code_valid(raw):
            error(f"  '{raw}' is not valid — must be exactly 3 alphanumeric characters.")
            continue
        if raw in existing_codes:
            error(f"  '{raw}' is already used by '{[k for k,v in codes.items() if v == raw][0]}'.")
            continue
        # Confirm
        confirm = input(f"{Colors.BOLD}  Confirm code '{raw}' for [{key}]? [y/N]: {Colors.RESET}").strip().lower()
        if confirm != "y":
            info("  Cancelled — try again.")
            continue
        break

    codes[key] = raw
    versions.setdefault(raw, "0.1.000")  # init counter only if brand-new code
    flash_cfg["hwrev_codes"] = codes
    flash_cfg["versions"] = versions
    with open(flash_cfg_path, "w", encoding="utf-8") as _fh:
        json.dump(flash_cfg, _fh, indent=2)
    success(f"Code '{raw}' registered for [{key}] and saved to .flash_config.json")
    return raw


def bump_hw_version(hw_code: str, flash_cfg: dict, flash_cfg_path: Path) -> str:
    """Bump the patch counter for hw_code in flash_cfg and return the full version string.

    Stored format: "major.minor.patch"  (e.g. "0.1.017")
    Returned format: "{hw_code}.major.minor.patch"  (e.g. "C02.0.1.018")
    """
    versions: dict = flash_cfg.setdefault("versions", {})
    cur = versions.get(hw_code, "0.1.000")
    parts = cur.split(".")
    if len(parts) == 3:
        try:
            new_patch = int(parts[2]) + 1
            if new_patch > 999:
                warning(f"Patch version at .999 limit for {hw_code} — keeping {cur}")
                new_ver = cur
            else:
                new_ver = f"{parts[0]}.{parts[1]}.{new_patch:03d}"
                versions[hw_code] = new_ver
                flash_cfg["versions"] = versions
                with open(flash_cfg_path, "w", encoding="utf-8") as _fh:
                    json.dump(flash_cfg, _fh, indent=2)
                success(f"Version bumped: {hw_code}.{cur} → {hw_code}.{new_ver}")
        except ValueError:
            new_ver = cur
            warning(f"Could not parse version '{cur}' for {hw_code} — building without bump")
    else:
        new_ver = cur

    return f"{hw_code}.{new_ver}"


class BuildSelector:
    def __init__(self, config_dir: Path):
        self.config_dir = config_dir
        self.boards: Dict = {}
        self.roles: Dict = {}
        self.cache_file = config_dir.parent / "cache" / "last_selection.json"
        self.cache_file.parent.mkdir(parents=True, exist_ok=True)
        
        self._load_configs()
    
    def _load_configs(self) -> None:
        """Load board and role configurations"""
        # Load boards
        boards_file = self.config_dir / "boards.json"
        if boards_file.exists():
            with open(boards_file, 'r', encoding='utf-8-sig') as f:
                config = json.load(f)
                self.boards = config.get("boards", {})
        
        # Load roles
        roles_file = self.config_dir / "roles.json"
        if roles_file.exists():
            with open(roles_file, 'r', encoding='utf-8-sig') as f:
                config = json.load(f)
                self.roles = config.get("roles", {})
    
    def _save_selection(self, board: str, hwrev: str, role: str) -> None:
        """Save selection to cache"""
        selection = {
            "board": board,
            "hwrev": hwrev,
            "role": role
        }
        with open(self.cache_file, 'w') as f:
            json.dump(selection, f, indent=2)
    
    def _load_last_selection(self) -> Optional[Tuple[str, str, str]]:
        """Load last selection from cache"""
        if self.cache_file.exists():
            try:
                with open(self.cache_file, 'r') as f:
                    sel = json.load(f)
                    return (sel.get("board"), sel.get("hwrev"), sel.get("role"))
            except:
                return None
        return None
    
    def list_boards(self) -> None:
        """Display available boards"""
        header("Available Boards")
        
        for board_id, board_info in self.boards.items():
            cprint(f"  {board_id:15} {board_info['name']}", Colors.CYAN)
            print(f"    {board_info['description']}")
            print(f"    Build System: {board_info['build_system']}")
            print()
    
    def select_board_interactive(self) -> str:
        """Interactive board selection"""
        header("Select Board")
        
        boards_list = list(self.boards.keys())
        
        for i, board in enumerate(boards_list, 1):
            info = self.boards[board]
            print(f"  [{i}] {board:15} - {info['name']}")
        
        while True:
            try:
                choice = input(f"\nSelect board [1-{len(boards_list)}]: ").strip()
                idx = int(choice) - 1
                if 0 <= idx < len(boards_list):
                    return boards_list[idx]
                else:
                    error("Invalid selection")
            except ValueError:
                error("Please enter a number")
    
    def select_hwrev_interactive(self, board: str) -> str:
        """Interactive hardware revision selection"""
        header(f"Select Hardware Revision ({board})")
        
        hwrevs = self.boards[board].get("hwrevs", [])
        if not hwrevs:
            error(f"No hardware revisions found for {board}")
            sys.exit(1)
        
        for i, hwrev_info in enumerate(hwrevs, 1):
            hwrev_id = hwrev_info['id']
            hwrev_name = hwrev_info['name']
            status = "[*] Active" if hwrev_info.get('active', False) else "[ ] Inactive"
            print(f"  [{i}] {hwrev_id:5} - {hwrev_name:30} ({status})")
        
        while True:
            try:
                choice = input(f"\nSelect hardware revision [1-{len(hwrevs)}]: ").strip()
                idx = int(choice) - 1
                if 0 <= idx < len(hwrevs):
                    return hwrevs[idx]['id']
                else:
                    error("Invalid selection")
            except ValueError:
                error("Please enter a number")
    
    def select_role_interactive(self, board: str) -> str:
        """Interactive role selection"""
        header(f"Select Device Role ({board})")
        
        available_roles = self.boards[board].get("available_roles", [])
        
        for i, role_id in enumerate(available_roles, 1):
            if role_id in self.roles:
                role_info = self.roles[role_id]
                print(f"  [{i}] {role_id:20} - {role_info['name']}")
                print(f"       {role_info['description']}")
            else:
                print(f"  [{i}] {role_id:20} - [Unknown role]")
        
        while True:
            try:
                choice = input(f"\nSelect role [1-{len(available_roles)}]: ").strip()
                idx = int(choice) - 1
                if 0 <= idx < len(available_roles):
                    return available_roles[idx]
                else:
                    error("Invalid selection")
            except ValueError:
                error("Please enter a number")
    
    def show_selection_summary(self, board: str, hwrev: str, role: str) -> None:
        """Display selection summary"""
        header("Build Configuration Summary")
        
        board_info = self.boards.get(board, {})
        role_info = self.roles.get(role, {})
        hwrev_info = None
        for hw in board_info.get("hwrevs", []):
            if hw['id'] == hwrev:
                hwrev_info = hw
                break
        
        print(f"  board:              {Colors.CYAN}{board}{Colors.RESET}")
        print(f"                         {board_info.get('description', '')}\n")
        
        print(f"  Hardware Revision:     {Colors.CYAN}{hwrev}{Colors.RESET}")
        if hwrev_info:
            print(f"                         {hwrev_info.get('name', '')}\n")
        
        print(f"  Device Role:           {Colors.CYAN}{role}{Colors.RESET}")
        print(f"                         {role_info.get('description', '')}\n")
        
        if role_info:
            print(f"  Components:")
            for comp in role_info.get('components', []):
                print(f"    - {comp}")
            print()
            
            print(f"  Features:")
            for feat in role_info.get('features', []):
                print(f"    - {feat}")
            print()
    
    def generate_build_config(self, board: str, hwrev: str, role: str) -> Dict:
        """Generate build configuration"""
        board_info = self.boards.get(board, {})
        role_info = self.roles.get(role, {})
        
        build_config = {
            "build_timestamp": __import__('datetime').datetime.now().isoformat(),
            "board": {
                "id": board,
                "name": board_info.get("name", "Unknown"),
                "build_system": board_info.get("build_system", ""),
                "target": board_info.get("target", ""),
                "idf_version": board_info.get("idf_version", ""),
                "project_path": board_info.get("project_path", "")
            },
            "hwrev": hwrev,
            "role": {
                "id": role,
                "name": role_info.get("name", "Unknown"),
                "components": role_info.get("components", []),
                "features": role_info.get("features", []),
                "config": role_info.get("default_config", {})
            },
            "source_dirs": board_info.get("source_dirs", [])
        }
        
        return build_config
    
    def run_build(self, board: str, hwrev: str, role: str, verbose: bool = False,
                  clean: bool = False, flash: str = None, monitor: str = None) -> int:
        """Execute build with selected configuration"""
        info(f"Starting build for {board} hwrev {hwrev} role {role}...")
        
        # Generate configuration
        build_config = self.generate_build_config(board, hwrev, role)
        
        # Save to cache
        self._save_selection(board, hwrev, role)

        # Resolve 3-char hardware code and bump per-code version counter.
        # Format: {hw_code}.major.minor.patch  e.g. "C02.0.1.018"
        flash_cfg_path = Path(__file__).parent.parent / ".flash_config.json"
        build_version = "UNK.0.1.001"
        if flash_cfg_path.exists():
            with open(flash_cfg_path, "r", encoding="utf-8") as _fh:
                flash_cfg = json.load(_fh)
            hw_code = resolve_hw_code(board, hwrev, flash_cfg, flash_cfg_path)
            build_version = bump_hw_version(hw_code, flash_cfg, flash_cfg_path)
        else:
            warning("No .flash_config.json found — building with version UNK.0.1.001")

        # Auto-scaffold role directory before invoking the compiler.
        # Without pds_process_action.c + usrset_defaults.h the linker fails with
        # 'undefined reference to pds_role_init' — after a full compile cycle.
        # Detecting and fixing it here saves that time.
        _hal_board_dir = self.boards.get(board, {}).get("hal_board", board)
        if scaffold_role_dir(_hal_board_dir, hwrev, role):
            warning(f"Role dir was missing — scaffolded: "
                    f"Device/pds/pds_hal/board/{_hal_board_dir}/{hwrev}/{role}/")
            warning("Edit pds_process_action.c to add telemetry wiring for this role.")

        # Determine build script based on board
        script_dir = Path(__file__).parent
        
        # Map board names to build systems
        board_lower = board.lower()
        if 'esp32' in board_lower:
            build_script = script_dir / "build_espidf.py"
            build_system = "esp-idf"
        elif 'efr32' in board_lower or 'silabs' in board_lower:
            build_script = script_dir / "build_silabs.py"
            build_system = "silabs"
        else:
            error(f"Unknown board: {board}")
            return 1
        
        if not build_script.exists():
            error(f"Build script not found: {build_script}")
            return 1
        
        # Check if we should use devcontainer (auto-prefer devcontainer if available)
        use_devcontainer = False
        container_path = get_devcontainer_path(board)
        
        if container_path and has_devcontainer_cli():
            # Auto-use devcontainer if available (no prompt)
            use_devcontainer = True
            success(f"Using devcontainer: {container_path.name}")
        elif container_path and not has_devcontainer_cli():
            # Devcontainer exists but CLI not installed
            warning(f"Found devcontainer but 'devcontainer' CLI not found")
            warning(f"Install with: npm install -g @devcontainers/cli")
            warning(f"Falling back to native build (may fail)")
        else:
            # No devcontainer found, use native
            info(f"Using native build (no devcontainer found)")
        
        if use_devcontainer:
            # Execute build inside devcontainer
            info(f"Building in devcontainer...")
            
            # Force remove old containers to ensure fresh one with new mounts
            info(f"Removing old container instances...")
            cleanup_cmd = f'docker ps -a -q | xargs docker rm -f 2>nul || exit /b 0'
            subprocess.run(cleanup_cmd, shell=True, text=True, bufsize=1, stderr=subprocess.DEVNULL, stdout=subprocess.DEVNULL)
            
            # Now start fresh container — capture stdout to extract containerId from JSON
            info(f"Starting fresh container with mounts...")
            up_cmd = f'devcontainer up --workspace-folder "{container_path}"'
            up_result = subprocess.run(up_cmd, shell=True, text=True, capture_output=True)
            container_id = None
            for _line in up_result.stdout.splitlines():
                _line = _line.strip()
                if _line.startswith('{'):
                    try:
                        _data = json.loads(_line)
                        container_id = _data.get('containerId')
                    except json.JSONDecodeError:
                        pass
                else:
                    print(_line)
            if up_result.stderr:
                print(up_result.stderr, end='')
            if up_result.returncode != 0:
                error("devcontainer up failed - is Docker Desktop running?")
                error("Start Docker Desktop, wait for it to be ready, then retry.")
                return up_result.returncode
            
            # Set up working build directory in container from read-only source mounts.
            # Always wipe /build first so there are no stale artefacts or wrong-target
            # sdkconfig files from a previous build (e.g. esp32c3 sdkconfig in an esp32 build).
            # Also wipe managed_components + dependencies.lock after the copy — the host may have
            # a stale lock from a different run. The component manager re-resolves from
            # idf_component.yml on each build, which is the source of truth.
            setup_cmd = (
                "rm -rf /build && "
                "mkdir -p /build && "
                "cp -r /src/main /build/ && "
                "cp -r /src/pds /build/ 2>/dev/null && "
                "rm -rf /build/main/build /build/main/sdkconfig /build/main/sdkconfig.old "
                "/build/main/managed_components /build/main/dependencies.lock /build/main/idf-component.lock && "
                # Windows-edited YAML files arrive with CRLF line endings which cause the
                # IDF component manager's YAML parser to silently drop dependencies.
                # Strip all \r from .yml / .yaml files after the copy.
                "find /build -name '*.yml' -o -name '*.yaml' | xargs -r sed -i 's/\\r//g'"
            )
            subprocess.run(f'devcontainer exec --workspace-folder "{container_path}" bash -c "{setup_cmd}"', 
                          shell=True, text=True, bufsize=1, stderr=subprocess.DEVNULL)
            
            # Now execute the build
            if 'esp32' in board_lower:
                # For ESP-IDF builds.
                # Read IDF_TARGET from .board_config so we handle all three board dirs.
                hal_dir = Path(__file__).parent.parent.parent / "Device" / "pds" / "pds_hal" / "board"
                # Use hal_board from config if available, else fall back to board key
                _hal_board = self.boards.get(board, {}).get("hal_board", board)
                board_cfg = hal_dir / _hal_board / ".board_config"
                idf_target = "esp32"  # safe fallback
                if board_cfg.exists():
                    for cfg_line in board_cfg.read_text(encoding="utf-8").splitlines():
                        cfg_line = cfg_line.strip()
                        if cfg_line.startswith("IDF_TARGET="):
                            idf_target = cfg_line.split("=", 1)[1].strip()
                            break

                build_parts = []
                # build/ and sdkconfig are already wiped by setup_cmd above.
                # Only run fullclean if --clean was explicitly requested.
                if clean:
                    build_parts.append("idf.py fullclean")
                # -D flags are global idf.py options — must come before the subcommand
                # IDF_TARGET env var selects the SoC without needing idf.py set-target
                # Map build-selector ids to actual HAL directory names.
                # board key in boards.json may differ from the hal_board name
                # passed on the command line, so also search by hal_board value.
                _board_data = self.boards.get(board) or next(
                    (v for v in self.boards.values() if v.get("hal_board") == board), {}
                )
                # hwrev passed directly from saved role config — use as-is unless boards.json
                # has an explicit dir override for legacy numbered revisions.
                _hwrev_id = hwrev[len("hwrev_"):] if hwrev.startswith("hwrev_") else hwrev
                _hwrev_info = next(
                    (h for h in _board_data.get("hwrevs", []) if h.get("id") == _hwrev_id),
                    {}
                )
                # Use explicit dir from config if present; otherwise use hwrev exactly as passed.
                _hwrev_dir = _hwrev_info.get("dir") or hwrev
                _role_dir = _hwrev_info.get("role_dirs", {}).get(role, role)
                build_parts.append(
                    f"IDF_TARGET={idf_target} idf.py -DPDS_HWREV={_hwrev_dir} -DPDS_ROLE={_role_dir} -DPROJECT_VER=\"{build_version}\" build"
                )
                # NOTE: flash/monitor are NOT added to the container command — COM ports are
                # Windows-only and invisible inside Docker.  We copy the binaries out after
                # the build and flash from the host using the local esptool.
                build_cmd = "/opt/esp/entrypoint.sh bash -c 'cd /build/main && " + " && ".join(build_parts) + "'"
            else:
                # For Silabs builds
                build_cmd = "cd /build/main && make"
            
            cmd = f'devcontainer exec --workspace-folder "{container_path}" bash -c "{build_cmd}"'
            
            info(f"Executing: devcontainer exec in {container_path.name}")
            
            # Execute with shell=True on Windows for devcontainer CLI (npm-installed)
            result = subprocess.run(cmd, shell=True, text=True, bufsize=1)

            # Copy build artifacts out of the container to dist/ on the Windows host.
            # We do this whenever the BUILD succeeded, regardless of whether flash was
            # requested — so the binaries are always available for manual re-flashing.
            if result.returncode == 0 and container_id and 'esp32' in board_lower:
                dist_dir = Path(__file__).parent.parent / "dist"
                dist_dir.mkdir(exist_ok=True)
                esp32_bins = [
                    ("/build/main/build/pds-device.bin",                     "pds-device.bin"),
                    ("/build/main/build/bootloader/bootloader.bin",          "bootloader.bin"),
                    ("/build/main/build/partition_table/partition-table.bin", "partition-table.bin"),
                    ("/build/main/build/ota_data_initial.bin",               "ota_data_initial.bin"),
                ]
                info("Copying build artifacts to dist/...")
                copy_ok = True
                for _src, _dst in esp32_bins:
                    _cp = subprocess.run(
                        f'docker cp {container_id}:{_src} "{dist_dir / _dst}"',
                        shell=True, text=True, capture_output=True
                    )
                    if _cp.returncode == 0:
                        _sz = (dist_dir / _dst).stat().st_size
                        success(f"  {_dst} ({_sz:,} bytes)")
                    else:
                        warning(f"  Failed to copy {_dst}: {_cp.stderr.strip()}")
                        copy_ok = False

                # Flash from the Windows host using the local Python esptool, so COM ports
                # are accessible.  esptool is bundled with ESP-IDF and also available via
                # `pip install esptool` in the project venv.
                if flash and copy_ok:
                    info(f"Flashing to {flash} from host...")
                    # Find the esptool-capable Python: prefer the workspace venv, fall back to
                    # sys.executable.  The system Python may not have esptool installed.
                    workspace_root = Path(__file__).parent.parent.parent
                    venv_python = workspace_root / ".venv" / "Scripts" / "python.exe"
                    if not venv_python.exists():
                        venv_python = workspace_root / ".venv" / "bin" / "python"
                    flash_python = str(venv_python) if venv_python.exists() else sys.executable
                    flash_cmd = (
                        f'"{flash_python}" -m esptool --chip {idf_target} -p {flash} -b 460800 '
                        f'--before default_reset --after hard_reset write_flash '
                        f'--flash_mode dio --flash_size 4MB '
                        f'0x1000 "{dist_dir / "bootloader.bin"}" '
                        f'0x8000 "{dist_dir / "partition-table.bin"}" '
                        f'0x10000 "{dist_dir / "pds-device.bin"}" '
                        f'0x2d0000 "{dist_dir / "ota_data_initial.bin"}"'
                    )
                    flash_result = subprocess.run(flash_cmd, shell=True, text=True, bufsize=1)
                    if flash_result.returncode != 0:
                        error("Flash failed — binaries are in PDS-BuildTools/dist/ for manual flashing")
                        return flash_result.returncode
                    success("Flash complete!")

            return result.returncode
        else:
            # Execute build script natively
            cmd = [sys.executable, str(build_script), "--board", board, "--hwrev", hwrev, "--role", role]
            if verbose:
                cmd.append("--verbose")
            if clean:
                cmd.append("--clean")
            if flash:
                cmd.extend(["--flash", flash])
            if monitor:
                cmd.extend(["--monitor", monitor])
            
            info(f"Executing: {' '.join(cmd)}")
        
        # On Windows, use shell=True for native commands as well
        use_shell = sys.platform == "win32"
        if use_shell:
            # Convert command list to string for shell execution on Windows
            cmd_str = " ".join(f'"{arg}"' if " " in str(arg) else str(arg) for arg in cmd)
            result = subprocess.run(cmd_str, shell=True, text=True, bufsize=1)
        else:
            result = subprocess.run(cmd, text=True, bufsize=1)
        
        return result.returncode
    
    def interactive_mode(self) -> int:
        """Run interactive selection mode"""
        header("PDS-AutomationSuite Build Selector")
        
        # Try to load last selection
        last_sel = self._load_last_selection()
        if last_sel and last_sel[0] in self.boards:
            print("Last selection found:")
            print(f"  board: {Colors.CYAN}{last_sel[0]}{Colors.RESET}")
            print(f"  Hardware: {Colors.CYAN}{last_sel[1]}{Colors.RESET}")
            print(f"  Role:     {Colors.CYAN}{last_sel[2]}{Colors.RESET}\n")
            
            choice = input("Use last selection? (y/n): ").strip().lower()
            if choice == 'y':
                return self.run_build(last_sel[0], last_sel[1], last_sel[2])
        
        # Interactive selection
        board = self.select_board_interactive()
        hwrev = self.select_hwrev_interactive(board)
        role = self.select_role_interactive(board)
        
        # Show summary
        self.show_selection_summary(board, hwrev, role)
        
        # Confirm
        print("\nProceed with build? (y/n): ", end='', flush=True)
        confirm = input().strip().lower()
        if confirm != 'y':
            warning("Build cancelled")
            return 0
        
        # Execute build
        return self.run_build(board, hwrev, role, verbose=False)

def main():
    parser = argparse.ArgumentParser(
        description="PDS-AutomationSuite Build Selector",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python build_selector.py                                    # Interactive mode
  python build_selector.py --list-boards                  # List available boards
  python build_selector.py --board esp32c3 --hwrev 001 --role aeroponics
        """
    )
    
    parser.add_argument("--list-boards", action="store_true",
                        help="List available boards and exit")
    parser.add_argument("--board", help="Select board directly")
    parser.add_argument("--hwrev", help="Select hardware revision directly")
    parser.add_argument("--role", help="Select device role directly")
    parser.add_argument("--verbose", "-v", action="store_true",
                        help="Verbose output")
    parser.add_argument("--clean", action="store_true",
                        help="Clean build (fullclean + set-target)")
    parser.add_argument("--flash", metavar="PORT",
                        help="Flash to device after build (e.g. COM3)")
    parser.add_argument("--monitor", metavar="PORT",
                        help="Monitor serial output (e.g. COM3)")
    
    args = parser.parse_args()
    
    # Find config directory (parent directory contains config/)
    script_dir = Path(__file__).parent
    config_dir = script_dir.parent / "config"
    
    if not config_dir.exists():
        error(f"Configuration directory not found: {config_dir}")
        sys.exit(1)
    
    selector = BuildSelector(config_dir)
    
    # Handle --list-boards
    if args.list_boards:
        selector.list_boards()
        return 0
    
    # Handle direct build specification
    if args.board and args.hwrev and args.role:
        # board validation - accept any board (discovery happens in go.py)
        # Just verify it looks like a board name (not empty/malformed)
        if not args.board or len(args.board) < 2:
            error(f"Invalid board name: {args.board}")
            sys.exit(1)

        # Pass hwrev as-is — saved roles use free-form IDs (e.g. HWTEST-001).
        # The hwrev_ prefix convention is for legacy numbered revisions only.
        hwrev = args.hwrev

        selector.show_selection_summary(args.board, hwrev, args.role)
        return selector.run_build(args.board, hwrev, args.role, args.verbose,
                                  clean=args.clean, flash=args.flash, monitor=args.monitor)
    
    # Interactive mode
    return selector.interactive_mode()

if __name__ == "__main__":
    sys.exit(main())
