

/**
 * @file pds_process_action.c
 * @brief Role init and process action handler for role: AERO-001 (Aero-001)
 * @note Auto-generated by PDS Role Builder on 2026-04-28 18:26 UTC
 *       Platform: esp32_node32s / hwrev_001
 */

#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "esp_err.h"
#include "nvs.h"

#include "pds_usrset.h"
#include "pds_telemetry.h"
#include "usrset_defaults.h"   /* generated: role-specific usrset defaults */

static const char *TAG = "AERO_001_ROLE";

/* ── Telemetry Provider ───────────────────────────────────────────────────── */
/**
 * Called by pds_telemetry_collect() (triggered by GET /status).
 * Populate @p packet with current sensor readings and actuator states.
 * Use pds_telemetry_add_adc(), pds_telemetry_add_pwm(), pds_telemetry_add_gpio().
 */
static esp_err_t AERO_001_telemetry_provider(pds_teldata_packet_t *packet)
{
    /*
     * AERO-001 sensor/actuator telemetry scaffold.
     *
     * Pin assignments and scaling factors below are EXAMPLES.
     * Update them to match the deployed h/w wiring for this role.
     *
     * Typical AERO-001 aeroponic controller layout:
     *   ADC: GPIO34 = EC (electrical conductivity), GPIO35 = pH
     *        GPIO32 = reservoir water temperature (NTC)
     *   PWM: GPIO25 = high-pressure mist pump, GPIO26 = LED strip
     *   GPIO: GPIO27 = float valve relay (1 = open), GPIO14 = aux solenoid
     *
     * Obtain real raw values via esp_adc_cal / driver GPIO read.
     * Replace the placeholder 0.0f values with actual hardware reads.
     */

    /* ── ADC sensors ────────────────────────────────────────────────── */
    /* EC sensor on GPIO34.  raw = adc1_get_raw(ADC1_CHANNEL_6); voltage = raw * 3.3f / 4095.0f */
    pds_telemetry_add_adc(packet, 34, 0, 0.0f, 0.0f, "EC");

    /* pH sensor on GPIO35.  raw = adc1_get_raw(ADC1_CHANNEL_7); voltage = raw * 3.3f / 4095.0f */
    pds_telemetry_add_adc(packet, 35, 0, 0.0f, 0.0f, "pH");

    /* Reservoir temp (NTC) on GPIO32. */
    pds_telemetry_add_adc(packet, 32, 0, 0.0f, 0.0f, "Temp_C");

    /* ── PWM actuators ──────────────────────────────────────────────── */
    /* Mist pump on GPIO25.  duty = ledc_get_duty(speed_mode, channel); */
    pds_telemetry_add_pwm(packet, 25, 0, 1000, "MistPump");

    /* LED strip on GPIO26. */
    pds_telemetry_add_pwm(packet, 26, 0, 5000, "LEDStrip");

    /* ── GPIO states ────────────────────────────────────────────────── */
    /* Float valve relay on GPIO27. state = gpio_get_level(27); */
    pds_telemetry_add_gpio(packet, 27, 0, "FloatValve");

    /* Auxiliary solenoid on GPIO14. */
    pds_telemetry_add_gpio(packet, 14, 0, "AuxSolenoid");

    return ESP_OK;
}

/* ── Role Init ────────────────────────────────────────────────────────────── */
/**
 * Called once during platform boot (pds_platform_init).
 * Initialises usrset defaults, loads saved values from NVS,
 * and registers the telemetry provider.
 */
esp_err_t pds_role_init(void)
{
    esp_err_t ret = pds_usrset_init(pds_usrset_defaults, PDS_USRSET_DEFAULTS_COUNT);
    if (ret != ESP_OK) {
        ESP_LOGW(TAG, "pds_usrset_init: %s", esp_err_to_name(ret));
        return ret;
    }

    ret = pds_usrset_load_nvs();
    if (ret == ESP_ERR_NVS_NOT_FOUND) {
        ESP_LOGI(TAG, "No saved usrset — using compiled defaults");
        ret = ESP_OK;
    } else if (ret != ESP_OK) {
        ESP_LOGW(TAG, "pds_usrset_load_nvs: %s", esp_err_to_name(ret));
        return ret;
    }

    pds_telemetry_register_provider(AERO_001_telemetry_provider);

    ESP_LOGI(TAG, "Role init complete — 3 usrset defaults");
    return ESP_OK;
}

/* ── Process Action (★ superseded by pipeline engine) ─────────────────────── *
 *
 * In the 3-layer binary pipeline architecture, automation logic is composed
 * in the PDS Role Editor and uploaded at runtime as binary blobs (NVS keys
 * "pipeline", "hw_vars", "settings"). pds_platform_loop() calls
 * pds_pipeline_engine_tick() to drive all block execution.
 *
 * This function is NOT called by pds_platform_loop() and should NOT be
 * used for custom logic. It is retained only for forward compatibility.
 */
esp_err_t pds_process_action(void)
{
    return ESP_OK;
}
