# Auto-generated by PDS Role Builder — 2026-04-28 18:26 UTC
# Peripheral drivers for role: AERO-001
# DO NOT EDIT — regenerate via: python PDS-Role/go.py --config AERO-001

set(PDS_PERIPH_TYPES "")
# No peripheral drivers required for this role
