/**
 * purge-test-users.ts
 *
 * Removes test/generated user accounts from the shared database, keeping only
 * permanent accounts (staff or explicitly-kept emails like dev@pds.local).
 *
 * A "test user" is any account whose email matches one of these patterns:
 *   - hmi-user-*@device.local   (auto-generated by HMI during dev/testing)
 *   - test-*@*                  (any manually seeded test account)
 *   - *@test.local              (any *.test.local address)
 *
 * Staff accounts are NOT exempt if they match a test email pattern — the email
 * pattern is the authoritative signal. (Some legacy auto-generated accounts were
 * incorrectly stored with isStaff = true.)
 *
 * Devices owned by test users are reassigned to dev@pds.local before deletion
 * so they are not orphaned (devices.ownerId has ON DELETE SET NULL).
 *
 * SAFETY: Refuses to run in production.
 *
 * Run:  npm run purge:test-users   (from DB-Central/)
 */

import "reflect-metadata";
import "dotenv/config";
import { DataSource } from "typeorm";

function buildDataSource(): DataSource {
  if (process.env.DATABASE_URL) {
    return new DataSource({
      type: "postgres",
      url: process.env.DATABASE_URL,
      ssl: process.env.DATABASE_URL.includes("railway") ? { rejectUnauthorized: false } : false,
      entities: [],
      synchronize: false,
    });
  }
  return new DataSource({
    type: "postgres",
    host: process.env.PGHOST ?? "localhost",
    port: parseInt(process.env.PGPORT ?? "5432", 10),
    database: process.env.PGDATABASE ?? "pds_marketplace",
    username: process.env.PGUSER ?? "pds",
    password: process.env.PGPASSWORD ?? "pds_dev_password",
    entities: [],
    synchronize: false,
  });
}

// Test-user email patterns. Add patterns here as new test generators emerge.
const TEST_PATTERNS = [
  "hmi-user-%@device.local",
  "test-%",
  "%@test.local",
];

// Ordered list of child tables to clear before deleting from users.
// Deepest dependencies first (tables that reference other dependent tables).
// Columns using ON DELETE SET NULL (e.g. devices.ownerId) are handled via
// the reassignment step below instead.
const CHILD_TABLE_CLEANUPS: Array<{ table: string; columns: string[] }> = [
  { table: "message_fees",             columns: ["senderId", "recipientId"] },
  { table: "messaging_fee_waivers",    columns: ["grantedByUserId", "grantedToUserId"] },
  { table: "reviews",                  columns: ["reviewerId"] },
  { table: "disputes",                 columns: ["filedBy"] },
  { table: "reports",                  columns: ["reporterUserId", "reportedUserId", "resolvedByUserId"] },
  { table: "notifications",            columns: ["userId", "senderId"] },
  { table: "notification_preferences", columns: ["userId"] },
  { table: "messages",                 columns: ["senderId", "recipientId"] },
  { table: "orders",                   columns: ["buyerId"] },
  { table: "favorites",                columns: ["userId"] },
  { table: "saved_searches",           columns: ["userId"] },
  { table: "bulletin_cards",           columns: ["userId"] },
  { table: "invoices",                 columns: ["userId"] },
  { table: "payouts",                  columns: ["userId"] },
  { table: "portfolio_images",         columns: ["userId"] },
  { table: "waitlist_entries",         columns: ["userId"] },
  { table: "products",                 columns: ["designerId"] },
  { table: "services",                 columns: ["providerId"] },
  { table: "designers",                columns: ["userId"] },
  { table: "producers",                columns: ["userId"] },
];

async function purge() {
  if (process.env.NODE_ENV === "production") {
    console.error("❌  Refusing to purge in production. Set NODE_ENV=development.");
    process.exit(1);
  }

  const ds = buildDataSource();
  await ds.initialize();

  const patternClauses = TEST_PATTERNS
    .map((_, i) => `email LIKE $${i + 1}`)
    .join(" OR ");

  const victims: Array<{ id: string }> = await ds.query(
    `SELECT id FROM users WHERE (${patternClauses})`,
    TEST_PATTERNS
  );

  if (victims.length === 0) {
    console.log("✅  No test users found. Nothing to delete.");
    await ds.destroy();
    return;
  }

  console.log(`🗑️  Found ${victims.length} test user(s) to remove.`);

  const ids = victims.map((v) => v.id);

  await ds.transaction(async (em) => {
    // Reassign devices owned by test users to dev@pds.local before deleting.
    const devAccount = await em.query(
      `SELECT id FROM users WHERE email = 'dev@pds.local' LIMIT 1`
    );
    if (devAccount.length > 0) {
      await em.query(
        `UPDATE devices SET "ownerId" = $1 WHERE "ownerId" = ANY($2::uuid[])`,
        [devAccount[0].id, ids]
      );
    }

    // Delete all child rows that reference these users
    for (const { table, columns } of CHILD_TABLE_CLEANUPS) {
      for (const col of columns) {
        await em.query(
          `DELETE FROM "${table}" WHERE "${col}" = ANY($1::uuid[])`,
          [ids]
        );
      }
    }

    await em.query(
      `DELETE FROM users WHERE id = ANY($1::uuid[])`,
      [ids]
    );
  });

  console.log(`✅  Purged ${ids.length} test user(s).`);

  const [remaining] = await ds.query(`SELECT count(*) as cnt FROM users`);
  console.log(`    Remaining users: ${remaining.cnt}`);

  await ds.destroy();
}

purge().catch((e) => {
  console.error("❌  Purge failed:", e.message);
  process.exit(1);
});
