

/**
 * @file pds_process_action.c
 * @brief Role init and process action handler for role: TEST-001 (JUNK-001)
 * @note Auto-generated by PDS Role Builder on 2026-04-26 22:46 UTC
 *       Platform: esp32c3_sm / HWTEST-001
 */

#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "esp_err.h"
#include "nvs.h"

#include "pds_usrset.h"
#include "pds_telemetry.h"
#include "usrset_defaults.h"   /* generated: role-specific usrset defaults */

static const char *TAG = "TEST_001_ROLE";

/* ── Telemetry Provider ───────────────────────────────────────────────────── */
/**
 * Called by pds_telemetry_collect() (triggered by GET /status).
 * Populate @p packet with current sensor readings and actuator states.
 * Use pds_telemetry_add_adc(), pds_telemetry_add_pwm(), pds_telemetry_add_gpio().
 */
static esp_err_t TEST_001_telemetry_provider(pds_teldata_packet_t *packet)
{
    /*
     * TEST-001 (esp32c3_sm) telemetry scaffold.
     *
     * ESP32-C3 has one ADC bank (ADC1, channels 0-4 on GPIO0-4).
     * Pin assignments below are EXAMPLES — update for actual test wiring.
     *
     *   ADC: GPIO0 = analog sensor 0, GPIO1 = analog sensor 1
     *   PWM: GPIO3 = test PWM output (LEDC ch0)
     *   GPIO: GPIO4 = test relay / LED output
     *
     * Replace the placeholder 0 / 0.0f values with real driver reads.
     */

    /* ── ADC ────────────────────────────────────────────────────────── */
    pds_telemetry_add_adc(packet, 0, 0, 0.0f, 0.0f, "Analog0");
    pds_telemetry_add_adc(packet, 1, 0, 0.0f, 0.0f, "Analog1");

    /* ── PWM ─────────────────────────────────────────────────────────── */
    pds_telemetry_add_pwm(packet, 3, 0, 1000, "PWM_Test");

    /* ── GPIO ────────────────────────────────────────────────────────── */
    pds_telemetry_add_gpio(packet, 4, 0, "Relay_Test");

    return ESP_OK;
}

/* ── Role Init ────────────────────────────────────────────────────────────── */
/**
 * Called once during platform boot (pds_platform_init).
 * Initialises usrset defaults, loads saved values from NVS,
 * and registers the telemetry provider.
 */
esp_err_t pds_role_init(void)
{
    esp_err_t ret = pds_usrset_init(pds_usrset_defaults, PDS_USRSET_DEFAULTS_COUNT);
    if (ret != ESP_OK) {
        ESP_LOGW(TAG, "pds_usrset_init: %s", esp_err_to_name(ret));
        return ret;
    }

    ret = pds_usrset_load_nvs();
    if (ret == ESP_ERR_NVS_NOT_FOUND) {
        ESP_LOGI(TAG, "No saved usrset — using compiled defaults");
        ret = ESP_OK;
    } else if (ret != ESP_OK) {
        ESP_LOGW(TAG, "pds_usrset_load_nvs: %s", esp_err_to_name(ret));
        return ret;
    }

    pds_telemetry_register_provider(TEST_001_telemetry_provider);

    ESP_LOGI(TAG, "Role init complete — 3 usrset defaults");
    return ESP_OK;
}

/* ── Process Action (★ superseded by pipeline engine) ─────────────────────── *
 *
 * In the 3-layer binary pipeline architecture, automation logic is composed
 * in the PDS Role Editor and uploaded at runtime as binary blobs (NVS keys
 * "pipeline", "hw_vars", "settings"). pds_platform_loop() calls
 * pds_pipeline_engine_tick() to drive all block execution.
 *
 * This function is NOT called by pds_platform_loop() and should NOT be
 * used for custom logic. It is retained only for forward compatibility.
 */
esp_err_t pds_process_action(void)
{
    return ESP_OK;
}
