import { IConfigSchema } from "../types.js";

/** Crop template presets — populates form defaults on selection */
export const cropTemplates: Record<string, Record<string, unknown>> = {
  tomatoes: {
    mistEnabled: true, mistIntervalSeconds: 30, mistDurationSeconds: 5,
    lightOnHour: 6, lightOffHour: 22,
    phTarget: 6.0, phHysteresis: 0.3,
    pump1DoseRate: 20, pump2DoseRate: 10, pump3DoseRate: 5, pump4DoseRate: 0,
    waterChangeMode: "time", waterChangeIntervalDays: 7,
  },
  lettuce: {
    mistEnabled: true, mistIntervalSeconds: 45, mistDurationSeconds: 3,
    lightOnHour: 6, lightOffHour: 20,
    phTarget: 6.2, phHysteresis: 0.3,
    pump1DoseRate: 15, pump2DoseRate: 5, pump3DoseRate: 3, pump4DoseRate: 0,
    waterChangeMode: "time", waterChangeIntervalDays: 10,
  },
  catnip: {
    mistEnabled: true, mistIntervalSeconds: 60, mistDurationSeconds: 4,
    lightOnHour: 6, lightOffHour: 20,
    phTarget: 6.3, phHysteresis: 0.3,
    pump1DoseRate: 10, pump2DoseRate: 5, pump3DoseRate: 2, pump4DoseRate: 0,
    waterChangeMode: "time", waterChangeIntervalDays: 10,
  },
  flowers: {
    mistEnabled: true, mistIntervalSeconds: 40, mistDurationSeconds: 5,
    lightOnHour: 6, lightOffHour: 22,
    phTarget: 5.8, phHysteresis: 0.3,
    pump1DoseRate: 15, pump2DoseRate: 15, pump3DoseRate: 10, pump4DoseRate: 0,
    waterChangeMode: "time", waterChangeIntervalDays: 7,
  },
  "marijuana-veg": {
    mistEnabled: true, mistIntervalSeconds: 20, mistDurationSeconds: 5,
    lightOnHour: 6, lightOffHour: 0,
    phTarget: 5.8, phHysteresis: 0.2,
    pump1DoseRate: 25, pump2DoseRate: 10, pump3DoseRate: 10, pump4DoseRate: 5,
    waterChangeMode: "volume", waterChangeVolumeGallons: 15,
  },
  "marijuana-flower": {
    mistEnabled: true, mistIntervalSeconds: 25, mistDurationSeconds: 5,
    lightOnHour: 8, lightOffHour: 20,
    phTarget: 6.0, phHysteresis: 0.2,
    pump1DoseRate: 10, pump2DoseRate: 25, pump3DoseRate: 20, pump4DoseRate: 5,
    waterChangeMode: "volume", waterChangeVolumeGallons: 20,
  },
};

export const configSchemas = new Map<string, IConfigSchema>([
  [
    "1.0.0",
    {
      version: "1.0.0",
      params: [
        {
          key: "cropTemplate",
          label: "Crop Template",
          type: "enum",
          options: ["none", ...Object.keys(cropTemplates)],
          defaultValue: "none",
          description: "Preset crop profile — populates other fields with recommended defaults",
        },
        {
          key: "mistEnabled",
          label: "Misting Enabled",
          type: "boolean",
          defaultValue: true,
          description: "Enable or disable misting cycle",
        },
        {
          key: "mistIntervalSeconds",
          label: "Mist Interval (seconds)",
          type: "range",
          options: [5, 600],
          defaultValue: 30,
          description: "Seconds between misting cycles",
        },
        {
          key: "mistDurationSeconds",
          label: "Mist Duration (seconds)",
          type: "range",
          options: [1, 60],
          defaultValue: 5,
          description: "How long each misting cycle runs",
        },
        {
          key: "lightOnHour",
          label: "Lights On (hour)",
          type: "range",
          options: [0, 23],
          defaultValue: 6,
          description: "Hour of day lights turn on (24h format)",
        },
        {
          key: "lightOffHour",
          label: "Lights Off (hour)",
          type: "range",
          options: [0, 23],
          defaultValue: 22,
          description: "Hour of day lights turn off (24h format)",
        },
        {
          key: "phTarget",
          label: "pH Target",
          type: "range",
          options: [4.0, 8.0],
          defaultValue: 6.0,
          description: "Target pH for nutrient solution",
        },
        {
          key: "phHysteresis",
          label: "pH Hysteresis",
          type: "range",
          options: [0.1, 1.0],
          defaultValue: 0.3,
          description: "pH hysteresis band (advanced)",
        },
        {
          key: "pump1Product",
          label: "Pump 1 — Nutrient Product",
          type: "enum",
          options: ["none", "general-hydro-flora-grow", "general-hydro-flora-micro", "general-hydro-flora-bloom", "fox-farm-grow-big", "fox-farm-tiger-bloom", "cal-mag", "ph-up", "ph-down"],
          defaultValue: "none",
          description: "Nutrient product loaded in pump 1",
        },
        {
          key: "pump1DoseRate",
          label: "Pump 1 — Dose Rate (ml/gal)",
          type: "range",
          options: [0, 50],
          defaultValue: 0,
          description: "Pump 1 dosing rate",
        },
        {
          key: "pump2Product",
          label: "Pump 2 — Nutrient Product",
          type: "enum",
          options: ["none", "general-hydro-flora-grow", "general-hydro-flora-micro", "general-hydro-flora-bloom", "fox-farm-grow-big", "fox-farm-tiger-bloom", "cal-mag", "ph-up", "ph-down"],
          defaultValue: "none",
          description: "Nutrient product loaded in pump 2",
        },
        {
          key: "pump2DoseRate",
          label: "Pump 2 — Dose Rate (ml/gal)",
          type: "range",
          options: [0, 50],
          defaultValue: 0,
          description: "Pump 2 dosing rate",
        },
        {
          key: "pump3Product",
          label: "Pump 3 — Nutrient Product",
          type: "enum",
          options: ["none", "general-hydro-flora-grow", "general-hydro-flora-micro", "general-hydro-flora-bloom", "fox-farm-grow-big", "fox-farm-tiger-bloom", "cal-mag", "ph-up", "ph-down"],
          defaultValue: "none",
          description: "Nutrient product loaded in pump 3",
        },
        {
          key: "pump3DoseRate",
          label: "Pump 3 — Dose Rate (ml/gal)",
          type: "range",
          options: [0, 50],
          defaultValue: 0,
          description: "Pump 3 dosing rate",
        },
        {
          key: "pump4Product",
          label: "Pump 4 — Nutrient Product",
          type: "enum",
          options: ["none", "general-hydro-flora-grow", "general-hydro-flora-micro", "general-hydro-flora-bloom", "fox-farm-grow-big", "fox-farm-tiger-bloom", "cal-mag", "ph-up", "ph-down"],
          defaultValue: "none",
          description: "Nutrient product loaded in pump 4",
        },
        {
          key: "pump4DoseRate",
          label: "Pump 4 — Dose Rate (ml/gal)",
          type: "range",
          options: [0, 50],
          defaultValue: 0,
          description: "Pump 4 dosing rate",
        },
        {
          key: "waterChangeMode",
          label: "Water Change Mode",
          type: "enum",
          options: ["time", "volume"],
          defaultValue: "time",
          description: "Trigger water change by time interval or by volume added",
        },
        {
          key: "waterChangeIntervalDays",
          label: "Water Change Interval (days)",
          type: "range",
          options: [1, 30],
          defaultValue: 7,
          description: "Days between water changes (time mode)",
        },
        {
          key: "waterChangeVolumeGallons",
          label: "Water Change Volume (gallons)",
          type: "range",
          options: [1, 100],
          defaultValue: 20,
          description: "Gallons added before triggering change (volume mode)",
        },
      ],
    },
  ],
]);
