

/**
 * @file pds_process_action.c
 * @brief Role init and process action handler for role: AERO-003 (Aero-003)
 * @note Auto-generated by PDS Role Builder on 2026-04-30 16:43 UTC
 *       Platform: esp32 / hwrev_001
 */

#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "esp_err.h"
#include "nvs.h"

#include "pds_usrset.h"
#include "pds_telemetry.h"
#include "usrset_defaults.h"   /* generated: role-specific usrset defaults */

static const char *TAG = "AERO_003_ROLE";

/* ── Telemetry Provider ───────────────────────────────────────────────────── */
/**
 * Called by pds_telemetry_collect() (triggered by GET /status).
 * Populate @p packet with current sensor readings and actuator states.
 * Use pds_telemetry_add_adc(), pds_telemetry_add_pwm(), pds_telemetry_add_gpio().
 */
static esp_err_t AERO_003_telemetry_provider(pds_teldata_packet_t *packet)
{
    /* TODO: fill in live sensor/actuator state */
    (void)packet;
    return ESP_OK;
}

/* ── Role Init ────────────────────────────────────────────────────────────── */
/**
 * Called once during platform boot (pds_platform_init).
 * Initialises usrset defaults, loads saved values from NVS,
 * and registers the telemetry provider.
 */
esp_err_t pds_role_init(void)
{
    esp_err_t ret = pds_usrset_init(pds_usrset_defaults, PDS_USRSET_DEFAULTS_COUNT);
    if (ret != ESP_OK) {
        ESP_LOGW(TAG, "pds_usrset_init: %s", esp_err_to_name(ret));
        return ret;
    }

    ret = pds_usrset_load_nvs();
    if (ret == ESP_ERR_NVS_NOT_FOUND) {
        ESP_LOGI(TAG, "No saved usrset — using compiled defaults");
        ret = ESP_OK;
    } else if (ret != ESP_OK) {
        ESP_LOGW(TAG, "pds_usrset_load_nvs: %s", esp_err_to_name(ret));
        return ret;
    }

    pds_telemetry_register_provider(AERO_003_telemetry_provider);

    ESP_LOGI(TAG, "Role init complete — 3 usrset defaults");
    return ESP_OK;
}

/* ── Process Action (★ superseded by pipeline engine) ─────────────────────── *
 *
 * In the 3-layer binary pipeline architecture, automation logic is composed
 * in the PDS Role Editor and uploaded at runtime as binary blobs (NVS keys
 * "pipeline", "hw_vars", "settings"). pds_platform_loop() calls
 * pds_pipeline_engine_tick() to drive all block execution.
 *
 * This function is NOT called by pds_platform_loop() and should NOT be
 * used for custom logic. It is retained only for forward compatibility.
 */
esp_err_t pds_process_action(void)
{
    return ESP_OK;
}
