# Auto-generated by PDS Role Builder — 2026-04-30 16:43 UTC
# Peripheral drivers for role: AERO-003
# DO NOT EDIT — regenerate via: python PDS-Role/go.py --config AERO-003

set(PDS_PERIPH_TYPES "dht22")
