# Auto-generated by PDS Role Builder — 2026-05-28 19:27 UTC
# Peripheral drivers for role: AERO-005
# DO NOT EDIT — regenerate via: python PDS-Role/go.py --config AERO-005

set(PDS_PERIPH_TYPES "sensor_ph;sensor_ec;dht22;pwm_output;pid;switch_output;led_addr;gpio_value;sensor_analog;gpio_input")
