# Auto-generated by PDS Role Builder — 2026-05-16 01:27 UTC
# Peripheral drivers for role: chiller-001
# DO NOT EDIT — regenerate via: python PDS-Role/go.py --config chiller-001

# WARNING: unknown peripheral type 'oled_ssd1306' — no driver registered
# WARNING: unknown peripheral type 'pwm_device' — no driver registered

set(PDS_PERIPH_TYPES
    "encoder_quadrature"
    "encoder_mapped"
    "sensor_analog"
    "pid"
    "pwm_output"
)
