/**
 * @file usrset_defaults.h
 * @brief Compile-time default values for user-settable variables — chiller-001 role
 *
 * AUTO-GENERATED by PDS-Role tool on 2026-05-16 01:27 UTC
 * Role:   chiller-001 (Chiller-60w-v1)
 * Target: esp32c3_sm / hwrev-002
 *
 * DO NOT EDIT — regenerate via PDS-Role tool or VS Code "Generate" button.
 *
 * Usage in pds_platform_init():
 * @code
 *   #include "usrset_defaults.h"
 *   pds_usrset_init(pds_usrset_defaults, PDS_USRSET_DEFAULTS_COUNT);
 *   pds_usrset_load_nvs();   // Override with user-saved values
 * @endcode
 */

#ifndef PDS_USRSET_DEFAULTS_H
#define PDS_USRSET_DEFAULTS_H

#include "pds_usrset.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Compile-time defaults for role: chiller-001
 *
 * Each entry: { "variable_name", default_float_value }
 * Names ≤ 31 chars. Values are float (use whole numbers for integer vars).
 *
 * To modify defaults, edit the role config in PDS-Role and regenerate.
 */
static const pds_usrset_default_t pds_usrset_defaults[] = {

    { "telemetry_interval_ms", 5000.0f },    /* Telemetry publish interval */

    { "cloud_push_interval_ms", 300000.0f },    /* Cloud telemetry push interval (ms) */

};

/**
 * Number of entries in pds_usrset_defaults[].
 * Passed as 'count' to pds_usrset_init().
 */
#define PDS_USRSET_DEFAULTS_COUNT \
    ((uint16_t)(sizeof(pds_usrset_defaults) / sizeof(pds_usrset_defaults[0])))

#ifdef __cplusplus
}
#endif

#endif /* PDS_USRSET_DEFAULTS_H */
